name: Poetry setup
description: Add poetry and install deps with cache
inputs:
  os:
    description: "Operating system"
    required: true
  python-version:
    description: "Python version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry config virtualenvs.create false
    - name: Poetry Version
      shell: bash
      id: poetry-version
      run: echo "version=$(poetry --version | grep -oP '[\d\.]+')" >> $GITHUB_OUTPUT
